### ISSUE TITLE
Stray "div" closing tag

### ISSUE THREAD

**Issue by alexfmpe** [RyanGlScott/RyanGlScott.github.io#6]
There's a text node with `</div>` in it at the end of the '2014' section in http://ryanglscott.github.io/archive/ .

**Comment by RyanGlScott** [comment]
Thanks for the bug report.

I'll be honest—I copied most of this site directly from the [Gaya](https://github.com/gayanvirajith/gaya) Jekyll template, and I know almost nothing about how the underlying HTML is generated (since it relies on Ruby code which, again, I know almost nothing about). If you are knowledgeable in this area and could offer a patch, that would be greatly appreciated.

**Comment by alexfmpe** [comment]
> I know almost nothing about how the underlying HTML is generated

Me too!
It seemed like it'd be easier to fix than explaining it in an issue, but it wasn't obvious at a glance how things were generated, so I just opened this.

**Comment by RyanGlScott** [comment]
Some crude experimentation with Jekyll led to this hack: 7dd46fa. As far as I can tell, that does the trick, so I'll deem this issue closed.
